'use client';
import { useState } from 'react';
import { Check, ArrowRight, PencilLine } from 'lucide-react';
import { DATASETS, gradeExam, percent } from '../lib/domain';
import { NumberField, MathText, Assumptions, Feedback, TaskLead, type TaskProps } from './shared';
import { GraphBoard } from './labs';
export function PolicyTable({training=false}:{training?:boolean}){
 const d=training?DATASETS.training:DATASETS.exam;
 return <div className="policy-data"><div className="table-wrap"><table><caption>院系内部的录取率</caption><thead><tr><th>院系</th><th>{training?'匿名':'新方案'} T=1</th><th>{training?'传统':'原方案'} T=0</th></tr></thead><tbody><tr><th>H · 高录取率</th><td>{d.h1*100}%</td><td>{d.h0*100}%</td></tr><tr><th>L · 低录取率</th><td>{d.l1*100}%</td><td>{d.l0*100}%</td></tr></tbody></table></div><div className="table-wrap"><table><caption>观察到的院系构成</caption><thead><tr><th>方案</th><th>H 占比</th><th>L 占比</th></tr></thead><tbody><tr><th>T=1</th><td>{percent(d.w1,0)}</td><td>{percent(1-d.w1,0)}</td></tr><tr><th>T=0</th><td>{percent(d.w0,0)}</td><td>{percent(1-d.w0,0)}</td></tr></tbody></table></div></div>;
}
type AnswerProps={answers:Record<string,string>;change:(k:string,v:string)=>void};
function Pick({name,label,options,answers,change}:AnswerProps&{name:string;label:string;options:[string,string][]}){
 return <fieldset className="exam-pick"><legend>{label}</legend>{options.map(([id,text])=><label key={id} className={answers[name]===id?'checked':''}><input type="radio" name={name} checked={answers[name]===id} onChange={()=>change(name,id)}/><span>{text}</span></label>)}</fieldset>;
}
function Factors({prefix,title,...p}:AnswerProps&{prefix:string;title:string}){
 const t=prefix.includes('new')?'1':'0';
 const given='T='+t;
 const compact='\\begin{aligned}&P(R\\mid '+given+')\\\\&=P(R\\mid '+given+',C=H)\\\\&\\quad\\times P(C=H\\mid '+given+')\\\\&\\quad+P(R\\mid '+given+',C=L)\\\\&\\quad\\times P(C=L\\mid '+given+')\\end{aligned}';
 return <div className="factors"><h4>{title}</h4><MathText tex={'P(R\\mid '+given+')=P(R\\mid '+given+',C=H)P(C=H\\mid '+given+')+P(R\\mid '+given+',C=L)P(C=L\\mid '+given+')'} compactTex={compact} block/><div className="factor-row">{[0,1,2,3].map((i)=><div className="factor-wrap" key={i}>{i>0&&<b>{i===2?'+':'×'}</b>}<NumberField label={['H条件率','H权重','L条件率','L权重'][i]} value={p.answers[prefix+i]||''} onChange={v=>p.change(prefix+i,v)} unit="" placeholder="小数"/></div>)}</div></div>;
}
function Linear({prefix,title,...p}:AnswerProps&{prefix:string;title:string}){
 return <div className="linear-input"><b>{title} =</b><NumberField label={title+' 常数项'} value={p.answers[prefix+'0']||''} onChange={v=>p.change(prefix+'0',v)} unit="" placeholder="小数"/><span>＋</span><NumberField label={title+' λ系数'} value={p.answers[prefix+'1']||''} onChange={v=>p.change(prefix+'1',v)} unit="λ" placeholder="小数"/></div>;
}
export function ExamQuestion({question,...p}:AnswerProps&{question:number}){
 if(question===1)return <><PolicyTable/><div className="calculation-fields"><NumberField label="新方案总体录取率" value={p.answers.q1_new||''} onChange={v=>p.change('q1_new',v)}/><NumberField label="原方案总体录取率" value={p.answers.q1_old||''} onChange={v=>p.change('q1_old',v)}/></div><Pick {...p} name="q1_direction" label="分组与合并的结论是什么关系？" options={[['same','各院系与总体方向完全相同'],['reversal','各院系新方案较高，总体却较低，出现辛普森反转'],['error','只要合并后不同，就一定是算错了']]}/></>;
 if(question===2)return <><PolicyTable/><p>把每个条件率与对应的权重填入组合机。所有系数使用小数。</p><Factors {...p} prefix="q2_new_" title="新方案 T=1"/><Factors {...p} prefix="q2_old_" title="原方案 T=0"/><Pick {...p} name="q2_roles" label="每项中的两个因子，分别是什么？" options={[['rate-weight','同院系内的录取率 × 该院系在该方案中的权重'],['rate-rate','两个院系的录取率相乘'],['weight-weight','两个院系的权重相乘']]}/><Pick {...p} name="q2_reason" label="总体反转的结构原因是？" options={[['composition','新方案80%来自低录取率L，原方案80%来自高录取率H'],['ability','新方案申请者一定能力更差'],['average','所有百分比必须简单平均']]}/></>;
 if(question===3)return <><div className="premise"><b>题目给定的机制假设</b><p>院系C影响审核方案T的分配，也影响录取R；我们研究T是否影响R。方向不是只由相关性推出的。</p></div><GraphBoard edges={(p.answers.q3_edges||'').split(',').filter(Boolean)} onChange={v=>p.change('q3_edges',v.join(','))}/><Pick {...p} name="q3_paths" label="哪一组正确区分目标与非目标路径？" options={[['target-backdoor','目标T→R；混杂路径T←C→R'],['opposite','目标R→T；其他都与比较无关'],['delete','只保留T→R，删除全部背景变量']]}/><Pick {...p} name="q3_control" label="下一步应怎样比较？" options={[['within-C','在同一院系C内比较两种方案'],['remove-R','删除录取结果R'],['overall','直接用两组总体录取率宣布因果效果']]}/></>;
 if(question===4)return <><PolicyTable/><Assumptions/><div className="shared-population"><b>共同目标人群</b><span>H：50%　L：50%</span><small>两种方案面对完全相同的院系结构。</small></div><div className="calculation-fields"><NumberField label="共同人群 · 新方案录取率" value={p.answers.q4_new||''} onChange={v=>p.change('q4_new',v)}/><NumberField label="共同人群 · 原方案录取率" value={p.answers.q4_old||''} onChange={v=>p.change('q4_old',v)}/><NumberField label="新方案减原方案" unit="个百分点" value={p.answers.q4_effect||''} onChange={v=>p.change('q4_effect',v)}/></div><Pick {...p} name="q4_reason" label="为什么与原来两组总体率的比较不同？" options={[['same-population','这里比较共同人群；原来的两组院系构成不同'],['changed-rate','标准化偷偷修改了组内录取率'],['always-causal','重新加权就能无条件证明因果']]}/></>;
 return <><PolicyTable/><Assumptions/><p>共同目标人群中H的比例为λ，L为1−λ，且0≤λ≤1。用小数填写一次函数的系数。</p><Linear {...p} prefix="q5_new_" title="R₁(λ)"/><Linear {...p} prefix="q5_old_" title="R₀(λ)"/><Linear {...p} prefix="q5_tau_" title="τ(λ)"/><div className="calculation-fields"><NumberField label="差值最小值" value={p.answers.q5_min||''} onChange={v=>p.change('q5_min',v)} unit="个百分点"/><NumberField label="差值最大值" value={p.answers.q5_max||''} onChange={v=>p.change('q5_max',v)} unit="个百分点"/></div><Pick {...p} name="q5_interpretation" label="怎样解释这个范围？" options={[['assumptions','在本模型及可比性等假设下始终为正；与不同结构群体的总体反转不矛盾'],['unconditional','这证明所有现实学校的新方案都更好'],['negative','观察到新方案总体率较低，所以标准化差值必定为负']]}/></>;
}
export const EXAM_STEPS=['发现反转','解释权重','因果结构','标准化','函数推广'] as const;
export function ExamPractice({question,prompt,...p}:TaskProps&{question:number;prompt?:string}){
 const answers=Object.fromEntries(Object.entries(p.state).filter(([k,v])=>typeof v==='string'&&k!=='feedback')) as Record<string,string>;
 const change=(k:string,v:string)=>p.patch({[k]:v,feedback:'',wrong:false});
 return <div><ol className="exam-progress" aria-label="五问递进进度">{EXAM_STEPS.map((n,i)=><li key={n} className={i+1===question?'current':i+1<question?'passed':''}><b>0{i+1}</b>{n}</li>)}</ol>{prompt&&<TaskLead>{prompt}</TaskLead>}<ExamQuestion question={question} answers={answers} change={change}/><button className="primary" onClick={()=>{const d=gradeExam(answers).dimensions[question-1],ok=d.score===d.max;p.patch({feedback:ok?'这一问已贯通。你获得了'+d.score+' / '+d.max+'分对应的完整思路。':d.advice,wrong:!ok});if(ok)p.complete();}}>核验本问 <Check size={16}/></button><Feedback state={p.state}/></div>;
}
export function ExamScore({answers,onEdit}:{answers:Record<string,string>;onEdit:()=>void}){
 const result=gradeExam(answers);
 return <section className="score-report"><div className="score-hero"><span>推理塔 · 能力报告</span><strong>{result.total}<small>/ 17</small></strong><h2>让每一个结论，都有来处。</h2><p>按实际作答点计分；开放表达不冒充自动语义判卷。</p></div><div className="score-dimensions">{result.dimensions.map(d=><div key={d.title}><div className="score-title"><h3>{d.title}</h3><b>{d.score} / {d.max}</b></div><div className="score-track"><i style={{width:(d.score/d.max*100)+'%'}}/></div><ul>{d.items.map(i=><li key={i.label}><span>{i.score===i.max?'✓':'○'} {i.label}</span><b>{i.score}/{i.max}</b></li>)}</ul>{d.score<d.max&&<p>{d.advice}</p>}</div>)}</div><button className="primary" onClick={onEdit}><PencilLine size={16}/>修改答卷，再次提交</button></section>;
}
export function IndependentExam({question,answers,submitted,change,setQuestion,onSubmit,onEdit}:{question:number;answers:Record<string,string>;submitted:boolean;change:(k:string,v:string)=>void;setQuestion:(n:number)=>void;onSubmit:()=>void;onEdit:()=>void}){
 const [confirm,setConfirm]=useState(false);
 if(submitted)return <ExamScore answers={answers} onEdit={onEdit}/>;
 return <div className="exam-mode"><div className="exam-nav">{EXAM_STEPS.map((n,i)=><button className={question===i+1?'active':''} key={n} onClick={()=>{setQuestion(i+1);setConfirm(false);}}><b>0{i+1}</b>{n}<small>{[3,4,3,4,3][i]}分</small></button>)}</div><p className="micro">独立答卷 · 不继承探索答案 · 可以空答提交 · 提交后显示分项反馈 · 所有记录仅保存在本机</p><ExamQuestion question={question} answers={answers} change={change}/><label className="open-answer"><span>我的解释 / 草稿（自我表达，不自动计分）</span><textarea value={answers['note_'+question]||''} onChange={e=>change('note_'+question,e.target.value)} placeholder="可以写下计算过程、假设或你还不确定的地方。"/></label><div className="exam-actions"><button className="secondary" disabled={question===1} onClick={()=>setQuestion(question-1)}>上一问</button>{question<5?<button className="primary" onClick={()=>setQuestion(question+1)}>保存，进入下一问 <ArrowRight size={16}/></button>:<button className="primary" onClick={()=>setConfirm(true)}>提交整份答卷 <Check size={16}/></button>}</div>{confirm&&<div className="submission-confirm" role="alert"><p>将按当前答案计算五项能力得分。空答记0分，提交后仍可以修改并重新提交。</p><button className="primary" onClick={()=>{setConfirm(false);onSubmit();}}>确认提交</button><button className="text-button" onClick={()=>setConfirm(false)}>继续检查</button></div>}</div>;
}
